[package]
name = "worlds_derive"
version = "0.1.0"
edition = "2024"
description = "Derive crate for Worlds Engine"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
