[package]
name = "worlds"
version = "0.1.1"
edition = "2024"
description = "The Worlds Game Engine"
license = "MIT"

[dependencies]
worlds_ecs = "0.1"

[workspace]
resolver = "2"
members = ["worlds_ecs", "worlds_derive", "benchmarks/ecs"]
