[package]
name = "worlds_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ptr = "0.12"
primitive-types = "0.12"
worlds_derive = { path = "../worlds_derive" }

[features]
default = ["many_components"]
many_components = []
